apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfohelsenettproxy
  namespace: default
  labels:
    team: {{team}}
spec:
  image: "docker.pkg.github.com/navikt/syfohelsenettproxy:{{tag}}"
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi
  vault:
    enabled: true
    paths:
      - kvPath: /azuread/data/dev/creds/pale-2
        mountPath: /secrets/azuread/pale-2
      - kvPath: /azuread/data/dev/creds/pale-2-regler
        mountPath: /secrets/azuread/pale-2-regler
      - kvPath: /kv/preprod/fss/syfohelsenettproxy/default
        mountPath: /secrets/default
  webproxy: true
  ingresses:
    - "https://syfohelsenettproxy.nais.preprod.local"
  env:
    - name: SECURITY_TOKEN_SERVICE_URL
      value: https://sts-q1.preprod.local/SecurityTokenServiceProvider/
    - name: HELSEPERSONELL_V1_ENDPOINT_URL
      value: https://pep-gw-q4.oera-q.local:9443/samhandler/helse/helsepersonell/v1
    - name: CLIENT_ID
      value: c18eba24-f676-47db-9a97-3c66e9304aee
    - name: AADACCESSTOKEN_URL
      value: https://login.microsoftonline.com/navq.onmicrosoft.com/oauth2/token
    - name: AADDISCOVERY_URL
      value: https://login.microsoftonline.com/navq.onmicrosoft.com/.well-known/openid-configuration
    - name: JWT_ISSUER
      value: https://sts.windows.net/966ac572-f5b7-4bbe-aa88-c76419c0f851/
    - name: SYFOSMREGLER_CLIENT_ID
      value: b0f159e9-71af-4a30-8c2b-a02f67b7905a
    - name: SYFOSMMOTTAK_CLIENT_ID
      value: 589446d0-4e9d-41be-ae18-b6d001a8a328
    - name: SYFOSMINFOTRYGD_CLIENT_ID
      value: b5f266e7-cf26-4688-abc3-f44d78f5702c
    - name: SYFOSMPAPIRREGLER_CLIENT_ID
      value: c35dd346-0d3d-4b68-b883-a324c0b1098d
    - name: SYFOSMPAPIRMOTTAK_CLIENT_ID
      value: a99ce657-bce8-4f11-8dd6-5624038f4820
    - name: PADM2REGLER_CLIENT_ID
      value: d9cb3ab1-39ac-4844-81ec-123f437575aa