apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfohelsenettproxy
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 1
  prometheus:
    enabled: true
    path: /internal/prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 512Mi
  azure:
    application:
      enabled: true
      tenant: nav.no
  accessPolicy:
    inbound:
      rules:
        - application: syfosmmottak
          namespace: teamsykmelding
          cluster: prod-gcp
        - application: syfosmregler
          namespace: teamsykmelding
          cluster: prod-gcp
        - application: syfosminfotrygd
          namespace: teamsykmelding
          cluster: prod-gcp
        - application: syfosmpapirmottak
          namespace: teamsykmelding
          cluster: prod-gcp
        - application: syfosmpapirregler
          namespace: teamsykmelding
          cluster: prod-gcp
        - application: smregistrering-backend
          namespace: teamsykmelding
          cluster: prod-gcp
        - application: pale-2-regler
          namespace: teamsykmelding
          cluster: prod-gcp
        - application: padm2
          namespace: teamsykefravr
          cluster: prod-gcp
        - application: hm-brille-api
          namespace: teamdigihot
          cluster: prod-gcp
        - application: pale-2-sak
          namespace: teamsykmelding
          cluster: prod-gcp
    outbound:
      rules:
        - application: syfohelsenettproxy-redis
  webproxy: true
  envFrom:
    - secret: syfohelsenettproxy-redis-password
  ingresses:
    - "https://syfohelsenettproxy.intern.nav.no"
  env:
    - name: HELSEPERSONELL_V1_ENDPOINT_URL
      value: https://ws.nhn.no/v2/HPR/Basic
