apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfohelsenettproxy
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 1
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 512Mi
  azure:
    application:
      enabled: true
      tenant: nav.no
  accessPolicy:
    inbound:
      rules:
        - application: syfosmmottak
        - application: syfosmmottak
          namespace: teamsykmelding
          cluster: prod-gcp
        - application: syfosmregler
        - application: syfosmregler
          namespace: teamsykmelding
          cluster: prod-gcp
        - application: syfosminfotrygd
          namespace: teamsykmelding
          cluster: prod-gcp
        - application: syfosmpapirmottak
        - application: syfosmpapirregler
        - application: smregistrering-backend
        - application: pale-2-regler
        - application: pale-2-regler
          namespace: teamsykmelding
          cluster: prod-gcp
        - application: padm2
          namespace: teamsykefravr
          cluster: prod-gcp
        - application: hm-brille-api
          namespace: teamdigihot
          cluster: prod-gcp
  vault:
    enabled: true
    paths:
      - kvPath: serviceuser/data/prod/srvsyfohelsenettproxy
        mountPath: /secrets/serviceuser
  webproxy: true
  envFrom:
    - secret: syfohelsenettproxy-redis-password
  ingresses:
    - "https://syfohelsenettproxy.nais.adeo.no"
    - "https://syfohelsenettproxy.prod-fss-pub.nais.io"
  env:
    - name: SECURITY_TOKEN_SERVICE_URL
      value: https://sts.adeo.no/SecurityTokenServiceProvider/
    - name: HELSEPERSONELL_V1_ENDPOINT_URL
      value: https://pep-gw.oera.no:9443/samhandler/helse/helsepersonell/v1
