name: Deploy to dev and prod
on:
  push:
    paths-ignore:
      - 'nais/redis/redis.yaml'
      - '.github/workflows/redis**'
    branches:
      - master

env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/syfohelsenettproxy:${{ github.sha }}

jobs:
  build-push-deploy:
    name: Checkout code and create docker tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Setup gradle dependency cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/.*gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Run tests
        run: |
          ./gradlew test
      - name: Build jar
        run: |
          ./gradlew shadowJar -x test
      - name: Build and publish Docker image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker build --tag ${IMAGE} .
          docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
          docker push ${IMAGE}
      - name: Deploy to Preprod
        uses: nais/deploy/actions/deploy@master
        env:
          APIKEY: ${{ secrets.TEAMSYKMELDING_DEPLOY_KEY }}
          CLUSTER: dev-fss
          RESOURCE: naiserator-dev.yaml
      - name: Deploy to Prod
        uses: nais/deploy/actions/deploy@master
        env:
          APIKEY: ${{ secrets.TEAMSYKMELDING_DEPLOY_KEY }}
          CLUSTER: prod-fss
          RESOURCE: naiserator-prod.yaml
